name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create SSH Key and Set Permissions
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > github.pem
          chmod 400 github.pem  # Correct permissions

      - name: Copy files to EC2 using SCP (Excluding github.pem)
        run: |
          scp -o StrictHostKeyChecking=no -i github.pem -r --exclude='github.pem' * ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/

      - name: Restart Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i github.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl restart nginx
          EOF
